export const SERVER_BASE_URL = import.meta.env.VITE_SERVER_BASE_URL;
export const SUPPORTED_LANGUAGES = [{
  value: "none",
  label: "Plain Text",
}, {
  value: "c",
  label: "C",
}, {
  value: "cpp",
  label: "C++",
}, {
  value: "css",
  label: "CSS",
}, {
  value: "git",
  label: "Git",
}, {
  value: "go",
  label: "Golang",
}, {
  value: "html",
  label: "HTML",
}, {
  value: "java",
  label: "Java",
}, {
  value: "js",
  label: "JavaScript",
}, {
  value: "json",
  label: "JSON",
}, {
  value: "jsx",
  label: "JSX",
}, {
  value: "kotlin",
  label: "Kotlin",
}, {
  value: "lua",
  label: "Lua",
}, {
  value: "md",
  label: "Markdown",
}, {
  value: "py",
  label: "Python",
}, {
  value: "rust",
  label: "Rust",
}, {
  value: "sh",
  label: "Shell",
}, {
  value: "sql",
  label: "SQL",
}, {
  value: "ts",
  label: "TypeScript",
}, {
  value: "tsx",
  label: "TSX",
}, {
  value: "url",
  label: "URL",
}, {
  value: "xml",
  label: "XML",
}];