export const SERVER_BASE_URL = import.meta.env.VITE_SERVER_BASE_URL;
export const SUPPORTED_LANGUAGES = {
  c: "C",
  cpp: "C++",
  css: "CSS",
  git: "Git",
  go: "Golang",
  html: "HTML",
  java: "Java",
  js: "JavaScript",
  json: "JSON",
  jsx: "JSX",
  kotlin: "Kotlin",
  lua: "Lua",
  md: "Markdown",
  py: "Python",
  rust: "Rust",
  sh: "Shell",
  sql: "SQL",
  ts: "TypeScript",
  tsx: "TSX",
  url: "URL",
  xml: "XML",
};
